services:
  - type: web
    name: vitador-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    autoDeploy: true
    envVars:
      - fromGroup: custom1
  - type: worker
    name: vitador-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_bot.py"
    autoDeploy: true
    envVars:
      - fromGroup: custom1
