# render.yaml
services:
  # Основной сервис нашего бота
  - type: web
    name: manus-analytics-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py main:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: manus-db
          property: connectionString

  # Сервис базы данных MongoDB
  - type: pserv
    name: manus-db
    # Указываем, что используем готовый Docker-образ
    image:
      url: mongo:latest # Используем официальный образ mongo последней версии
    plan: free
    # Диск для хранения данных
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 1
