# render.yaml (v3.0 - "The Atlas Protocol")
services:
  - type: web
    name: manus-analytics-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py main:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
      # IMPORTANT: BOT_TOKEN, ADMIN_ID, and DATABASE_URL are now expected
      # to be set manually in the Render.com Environment UI.
      # This file no longer attempts to define them.
