# This Blueprint describes ONLY the bot worker.
services:
  - type: worker
    name: manus-analytics-bot-worker  # New, clear name
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_bot.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      # BOT_TOKEN, ADMIN_ID, DATABASE_URL must be set in Render Environment
