services:
  - type: web
    name: manus-analytics-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    healthCheckPath: /health
    envVars:
      - fromGroup: manus-analytics-secrets
      - key: PYTHON_VERSION
        value: 3.11.5
