services:
  # Веб-сервис для поддержания активности (требование Render Free Tier)
  - type: web
    name: vitador-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    autoDeploy: true
    envVars:
      - fromGroup: custom1 # Используем актуальную группу переменных

  # Воркер для запуска самого Telegram-бота
  - type: worker
    name: vitador-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - fromGroup: custom1 # Используем ту же актуальную группу переменных
