services:
  - type: worker
    name: manus-analytics-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_bot.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
