services:
  - type: web
    name: manus-analytics-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py main:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
      # Все секреты (BOT_TOKEN, ADMIN_ID, DATABASE_URL)
      # теперь будут задаваться ИСКЛЮЧИТЕЛЬНО вручную
      # в веб-интерфейсе Render для максимальной безопасности и гибкости.
